### ISSUE TITLE
[Bug]: The relationship graph often fails to display properly.

### ISSUE THREAD

**Issue by Drean21** [KosmosisDire/obsidian-webpage-export#392]
### What happened?

graph-wasm.js:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 's')
    at Module._malloc (graph-wasm.js:1:12863)
    at GraphAssembly.init (graph-view.js:1:843)
    at Object.initializeGraphView [as onRuntimeInitialized] (graph-view.js:1:8142)
    at graph-view.js:1:15486
    at o.<computed> (userscript.html?name=%25E8%25AE%25A1%25E6%2597%25B6%25E5%2599%25A8%25E6%258E%258C%25E6%258E%25A7%25E8%2580%2585%257C%25E8%25A7%2586%25E9%25A2%2591%25E5%25B9%25BF%25E5%2591%258A%25E8%25B7%25B3%25E8%25BF%2587%257C%25E8%25A7%2586%25E9%25A2%2591%25E5%25B9%25BF%25E5%2591%258A%25E5%258A%25A0%25E9%2580%259F%25E5%2599%25A8.user.js&id=7c199628-3c4f-4d8a-a409-411a364d91da:44:29758)

### Reproduction

The error code mentioned above frequently occurs when opening the website, resulting in the right sidebar relationship graph unable to display properly.

### Version

1.8.1-1B

### Operating System

win11

### Obsidian Version

v1.5.8

### Relevant log output

```yaml
N/A
```

**Comment by KosmosisDire** [comment]
I have only seen this bug occur on Safari on IOS. What browser are you using? You didn't fill it out in the form. Have you tried other browsers?

**Comment by Drean21** [comment]
> I have only seen this bug occur on Safari on IOS. What browser are you using? You didn't fill it out in the form. Have you tried other browsers?我只在 IOS 上的 Safari 上看到过这个错误。你使用的是什么浏览器？你没有在表格中填写。您尝试过其他浏览器吗？

I have tried both Edge and Google Chrome browsers, and this error may occur in either. However, it is not guaranteed to happen every time. Additionally, when I encounter this issue, pressing Ctrl+F5 may sometimes restore the display, but simply switching articles generally does not restore the display of the relationship graph.

**Comment by Drean21** [comment]
> > I have only seen this bug occur on Safari on IOS. What browser are you using? You didn't fill it out in the form. Have you tried other browsers?我只在 IOS 上的 Safari 上看到过这个错误。你使用的是什么浏览器？你没有在表格中填写。您尝试过其他浏览器吗？
> 
> I have tried both Edge and Google Chrome browsers, and this error may occur in either. However, it is not guaranteed to happen every time. Additionally, when I encounter this issue, pressing Ctrl+F5 may sometimes restore the display, but simply switching articles generally does not restore the display of the relationship graph.

I have tried multiple times and found that pressing Ctrl+F5 can generally restore the display, but regular page refreshes cannot. After the restoration, there are usually no further issues.

**Comment by KosmosisDire** [comment]
Is it possible for you to share a link to your website so I can test it? I have never encountered this

**Comment by Drean21** [comment]
> Is it possible for you to share a link to your website so I can test it? I have never encountered this您可以分享您网站的链接以便我测试吗？我从来没有遇到过这个

This is a frustrating situation. I haven't encountered this issue today despite opening it multiple times. I'm starting to suspect it might be a problem with my own network.😂

**Comment by Drean21** [comment]
> > Is it possible for you to share a link to your website so I can test it? I have never encountered this您可以分享您网站的链接以便我测试吗？我从来没有遇到过这个
> 
> This is a frustrating situation. I haven't encountered this issue today despite opening it multiple times. I'm starting to suspect it might be a problem with my own network.😂这是一个令人沮丧的情况。尽管我打开了多次，但今天还没有遇到这个问题。我开始怀疑可能是我自己的网络有问题。😂

I may have an idea of what's going on. This could be caused by the button I added in my head.html file for redirecting to the homepage.

**Comment by Drean21** [comment]
> > > Is it possible for you to share a link to your website so I can test it? I have never encountered this您可以分享您网站的链接以便我测试吗？我从来没有遇到过这个
> > 
> > 
> > This is a frustrating situation. I haven't encountered this issue today despite opening it multiple times. I'm starting to suspect it might be a problem with my own network.😂这是一个令人沮丧的情况。尽管我打开了多次，但今天还没有遇到这个问题。我开始怀疑可能是我自己的网络有问题。😂
> 
> I may have an idea of what's going on. This could be caused by the button I added in my head.html file for redirecting to the homepage.我可能知道发生了什么事。这可能是由我在 head.html 文件中添加的用于重定向到主页的按钮引起的。

When I switch back to the homepage using `window.location.href`, it seems that the elements of the relationship graph are not reloading. Here is the source code I added:

```html
<div class="cmdr status-bar-item clickable-icon" aria-label-position="top" aria-label="打开主页" style="color: inherit" onclick="window.location.href='/';">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="svg-icon lucide-home">
        <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
        <polyline points="9 22 9 12 15 12 15 22"></polyline>
    </svg>
</div>
```

**Comment by KosmosisDire** [comment]
Okay I'll check if I can reproduce this. It is possible there is something I can do to make it more resillient to changes
